stages:
  - build
  - test
  - package

build_job:
  stage: build
  script:
    - chmod +x cicd/build.sh
    - ./cicd/build.sh
  artifacts:
    paths:
      - usr/bin/bubble_sort_program

test_job:
  stage: test
  script:
    - chmod +x cicd/test.sh
    - ./cicd/test.sh

package_job:
  stage: package
  script:
    - chmod +x cicd/package.sh
    - ./cicd/package.sh
  artifacts:
    paths:
      - usr/bin/bubble_sort_program.deb
