name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build the project
        run: |
          make

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make test script executable
        run: chmod +x ./cicd/test.sh

      - name: Run tests
        run: |
          ./cicd/test.sh

  package:
    runs-on: ubuntu-latest
    needs: [test] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files in cicd directory
        run: ls -la cicd

      - name: Make package script executable
        run: chmod +x cicd/package.sh

      - name: Run package script
        run: ./cicd/package.sh

      - name: Upload deb package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: bubble_sort
          path: bubble_sort.deb  

  deploy:
    runs-on: ubuntu-latest
    needs: [package] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download deb package artifact
        uses: actions/download-artifact@v2
        with:
          name: bubble_sort

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t dora713/bubble_sort .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}   

      - name: Push Docker image
        run: |
          docker push dora713/bubble_sort
