name: CI/CD Pipeline

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build the project
        run: |
          make

      - name: Run tests
        run: |
          chmod +x cicd/test.sh
          ./cicd/test.sh

      - name: Package into .deb
        run: |
          chmod +x cicd/package.sh
          ./cicd/package.sh

      - name: Build Docker image
        run: |
          docker build -t my-image .

      - name: Run Docker container
        run: |
          docker run --name my-container my-image

      - name: Check if container is running
        if: success() # Этот шаг выполнится только если предыдущий шаг был успешным
        run: |
          echo "Container is running successfully."

      - name: Handle failure
        if: failure() # Этот шаг выполнится только если предыдущий шаг завершился с ошибкой
        run: |
          echo "Error occurred while running the container."

      - name: Upload .deb package
        uses: actions/upload-artifact@v4  
        with:
          name: bubble-sort-program
          path: bubble_sort.deb
