name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запускается при пуше в ветку main
  pull_request:
    branches:
      - master  # Запускается при создании PR в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t Dora20152/bubble_sort .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push Dora20152/bubble_sort

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: chmod +x ./cicd/test.sh
