name: CI/CD Pipeline

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-image .

      - name: Run Docker container
        run: |
          docker run --name my-container my-image

      - name: Check if container is running
        if: success() # Этот шаг выполнится только если предыдущий шаг был успешным
        run: |
          echo "Container is running successfully."

      - name: Handle failure
        if: failure() # Этот шаг выполнится только если предыдущий шаг завершился с ошибкой
        run: |
          echo "Error occurred while running the container."
