name: CI/CD Pipeline

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build the project
        run: |
          make

      - name: Run tests
        run: |
          chmod +x cicd/test.sh
          ./cicd/test.sh

      - name: Package into .deb
        run: |
          chmod +x cicd/package.sh
          ./cicd/package.sh

      - name: Upload .deb package
        uses: actions/upload-artifact@v4  
        with:
          name: bubble-sort-program
          path: bubble_sort.deb

      - name: Notify success
        if: success()
        run: echo "Build and tests completed successfully!"

      - name: Notify failure
        if: failure()
        run: echo "Build or tests failed. Please check the logs."
